[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$0hojxFjL.d97b40xpnRO6Q$pdM12IQuYxjrL//2c9XaiKAmnvRcWaLPenCUcjJDq0AmnMgpRRJeuB9QXyMf8MczvRsQYuNQMLJdKEEPqUZYOw

